#!/bin/sh -e

show_usage() {
    echo "Description: reboot guard wrapper"
	echo "Hostname   : $(hostname)"
	echo "Script saved in $(readlink -f $0)"
    echo "Usage: reboot [OPTIONS]"
    echo "[OPTIONS]"
    echo "    -d      dry-run"
    echo "    -f      reboot"
    echo "    -h      Show this message."
    exit $1
}

check_vm() {
  set +e
  which virsh 2>&1 >/dev/null
  if [ $? -eq 0 ];then
    if [ $(virsh list --state-running --name|wc -l) -ge 2 ];then
      echo "virsh vm is runnning."
      exit 1
    fi
  fi
  set -e
}

check_docker() {
  which docker 2>&1 >/dev/null
  if [ $? -eq 0 ];then
    if [ $(docker ps -q |wc -l) -ne 0 ];then
      echo "docker container is runnning."
      exit 1
    fi
  fi
}

__DRY_RUN=
__FORCE_REBOOT=
__COMMAND=

while getopts dfh OPTION; do
    case $OPTION in
        d)
            __DRY_RUN=1
            ;;
        f)
            __FORCE_REBOOT=1
            __COMMAND="/sbin/reboot"
            ;;
        h)
            show_usage 0
            ;;
        \?)
            show_usage 1
            ;;
    esac
done

[ -n "${__DRY_RUN}" ] \
  && echo "dryrun: $__COMMAND"

[ -z "${__FORCE_REBOOT}" ] \
  && show_usage 1

[ -z "${__DRY_RUN}" -a -n "${__FORCE_REBOOT}" ] \
  && check_vm \
  && check_docker \
  && $__COMMAND
